export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: { char: string; keywords: string }[];
}

/** Jeu d'emojis complet organisé par catégorie, avec mots-clés en français pour la recherche. */
export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Émotions",
    icon: "😊",
    emojis: [
      { char: "😀", keywords: "sourire content heureux" },
      { char: "😃", keywords: "sourire content heureux" },
      { char: "😄", keywords: "sourire content heureux rire" },
      { char: "😁", keywords: "sourire content dents" },
      { char: "😆", keywords: "rire mdr" },
      { char: "😅", keywords: "rire gêne sueur" },
      { char: "🤣", keywords: "mort de rire mdr" },
      { char: "😂", keywords: "pleure de rire mdr larmes" },
      { char: "🙂", keywords: "sourire léger" },
      { char: "🙃", keywords: "sourire renversé" },
      { char: "😉", keywords: "clin d'œil" },
      { char: "😊", keywords: "sourire content timide" },
      { char: "😇", keywords: "ange innocent saint" },
      { char: "🥰", keywords: "amour cœurs adorable" },
      { char: "😍", keywords: "amour yeux cœur" },
      { char: "🤩", keywords: "yeux étoiles fan" },
      { char: "😘", keywords: "bisou baiser" },
      { char: "😗", keywords: "bisou" },
      { char: "☺️", keywords: "sourire content" },
      { char: "😚", keywords: "bisou fermé" },
      { char: "😙", keywords: "bisou sourire" },
      { char: "🥲", keywords: "sourire larme" },
      { char: "😋", keywords: "délicieux miam" },
      { char: "😛", keywords: "langue tirée" },
      { char: "😜", keywords: "clin d'œil langue" },
      { char: "🤪", keywords: "fou dingue" },
      { char: "😝", keywords: "langue yeux fermés" },
      { char: "🤑", keywords: "argent dollars" },
      { char: "🤗", keywords: "câlin accolade" },
      { char: "🤭", keywords: "main bouche surpris" },
      { char: "🤫", keywords: "silence chut" },
      { char: "🤔", keywords: "réflexion pense" },
      { char: "🤐", keywords: "bouche fermée zip" },
      { char: "🤨", keywords: "sourcil levé doute" },
      { char: "😐", keywords: "neutre" },
      { char: "😑", keywords: "sans expression" },
      { char: "😶", keywords: "sans bouche silence" },
      { char: "😏", keywords: "sourire narquois" },
      { char: "😒", keywords: "blasé ennui" },
      { char: "🙄", keywords: "yeux levés exaspéré" },
      { char: "😬", keywords: "grimace gêne" },
      { char: "😮‍💨", keywords: "soupir" },
      { char: "🤥", keywords: "menteur nez" },
      { char: "😌", keywords: "soulagé serein" },
      { char: "😔", keywords: "triste pensif" },
      { char: "😪", keywords: "fatigué somnolent" },
      { char: "🤤", keywords: "bave" },
      { char: "😴", keywords: "dort sommeil" },
      { char: "😷", keywords: "masque malade" },
      { char: "🤒", keywords: "fièvre malade thermomètre" },
      { char: "🤕", keywords: "blessé tête bandage" },
      { char: "🤢", keywords: "nausée dégoût" },
      { char: "🤮", keywords: "vomi malade" },
      { char: "🥵", keywords: "chaud sueur" },
      { char: "🥶", keywords: "froid gelé" },
      { char: "😵", keywords: "étourdi assommé" },
      { char: "😵‍💫", keywords: "étourdi vertige" },
      { char: "🤯", keywords: "tête explose choc" },
      { char: "🤠", keywords: "cowboy chapeau" },
      { char: "🥳", keywords: "fête célébration anniversaire" },
      { char: "🥸", keywords: "déguisement lunettes" },
      { char: "😎", keywords: "cool lunettes soleil" },
      { char: "🤓", keywords: "geek lunettes intello" },
      { char: "🧐", keywords: "monocle curieux" },
      { char: "😕", keywords: "confus perplexe" },
      { char: "😟", keywords: "inquiet soucieux" },
      { char: "🙁", keywords: "triste" },
      { char: "☹️", keywords: "triste" },
      { char: "😮", keywords: "surpris étonné" },
      { char: "😯", keywords: "surpris silencieux" },
      { char: "😲", keywords: "choqué étonné" },
      { char: "😳", keywords: "gêné rougi" },
      { char: "🥺", keywords: "yeux suppliants triste" },
      { char: "😦", keywords: "figé surpris" },
      { char: "😧", keywords: "angoissé" },
      { char: "😨", keywords: "peur effrayé" },
      { char: "😰", keywords: "anxieux sueur froide" },
      { char: "😥", keywords: "triste déçu soulagé" },
      { char: "😢", keywords: "pleure triste larme" },
      { char: "😭", keywords: "pleure fort sanglot" },
      { char: "😱", keywords: "cri peur horreur" },
      { char: "😖", keywords: "confus douleur" },
      { char: "😣", keywords: "persévère effort" },
      { char: "😞", keywords: "déçu triste" },
      { char: "😓", keywords: "sueur épuisé" },
      { char: "😩", keywords: "épuisé fatigué" },
      { char: "😫", keywords: "épuisé fatigué" },
      { char: "🥱", keywords: "bâillement fatigue" },
      { char: "😤", keywords: "colère frustration fierté" },
      { char: "😡", keywords: "colère rouge fâché" },
      { char: "😠", keywords: "fâché colère" },
      { char: "🤬", keywords: "colère jure symboles" },
      { char: "😈", keywords: "diable malicieux" },
      { char: "👿", keywords: "diable colère" },
      { char: "💀", keywords: "mort crâne" },
      { char: "☠️", keywords: "mort danger" }
    ]
  },
  {
    id: "gestures",
    label: "Gestes",
    icon: "👍",
    emojis: [
      { char: "👋", keywords: "salut coucou main" },
      { char: "🤚", keywords: "main levée stop" },
      { char: "🖐️", keywords: "main ouverte stop" },
      { char: "✋", keywords: "main stop" },
      { char: "🖖", keywords: "vulcain star trek" },
      { char: "👌", keywords: "ok parfait" },
      { char: "🤌", keywords: "geste italien pincé" },
      { char: "🤏", keywords: "petit pincé" },
      { char: "✌️", keywords: "victoire paix" },
      { char: "🤞", keywords: "croiser les doigts chance" },
      { char: "🤟", keywords: "je t'aime signe" },
      { char: "🤘", keywords: "rock corne" },
      { char: "🤙", keywords: "appelle moi" },
      { char: "👈", keywords: "gauche pointer" },
      { char: "👉", keywords: "droite pointer" },
      { char: "👆", keywords: "haut pointer" },
      { char: "🖕", keywords: "doigt d'honneur" },
      { char: "👇", keywords: "bas pointer" },
      { char: "☝️", keywords: "index levé" },
      { char: "👍", keywords: "pouce en l'air ok super" },
      { char: "👎", keywords: "pouce en bas non" },
      { char: "✊", keywords: "poing fermé solidarité" },
      { char: "👊", keywords: "poing coup" },
      { char: "🤛", keywords: "poing gauche" },
      { char: "🤜", keywords: "poing droit" },
      { char: "👏", keywords: "applaudir bravo" },
      { char: "🙌", keywords: "mains levées célébration" },
      { char: "👐", keywords: "mains ouvertes câlin" },
      { char: "🤲", keywords: "mains ouvertes prière offrande" },
      { char: "🙏", keywords: "prière merci svp" },
      { char: "✍️", keywords: "écrire" },
      { char: "💪", keywords: "muscle force" },
      { char: "🦵", keywords: "jambe" },
      { char: "🦶", keywords: "pied" },
      { char: "👂", keywords: "oreille écoute" },
      { char: "👃", keywords: "nez" },
      { char: "👀", keywords: "yeux regarder" },
      { char: "👁️", keywords: "œil" },
      { char: "🧠", keywords: "cerveau intelligence" },
      { char: "🦷", keywords: "dent" },
      { char: "👶", keywords: "bébé" },
      { char: "🧒", keywords: "enfant" },
      { char: "👦", keywords: "garçon" },
      { char: "👧", keywords: "fille" },
      { char: "🧑", keywords: "personne adulte" },
      { char: "👨", keywords: "homme" },
      { char: "👩", keywords: "femme" },
      { char: "🧓", keywords: "personne âgée" },
      { char: "👴", keywords: "vieil homme" },
      { char: "👵", keywords: "vieille femme" },
      { char: "🙋", keywords: "lève la main" },
      { char: "🙋‍♂️", keywords: "homme lève la main" },
      { char: "🙋‍♀️", keywords: "femme lève la main" },
      { char: "🤦", keywords: "facepalm désespoir" },
      { char: "🤦‍♂️", keywords: "homme facepalm" },
      { char: "🤦‍♀️", keywords: "femme facepalm" },
      { char: "🤷", keywords: "hausse les épaules" },
      { char: "🤷‍♂️", keywords: "homme hausse épaules" },
      { char: "🤷‍♀️", keywords: "femme hausse épaules" },
      { char: "💃", keywords: "danse femme" },
      { char: "🕺", keywords: "danse homme" },
      { char: "🚶", keywords: "marche" },
      { char: "🏃", keywords: "course" },
      { char: "🧎", keywords: "à genoux" },
      { char: "🧍", keywords: "debout" }
    ]
  },
  {
    id: "hearts",
    label: "Cœurs",
    icon: "❤️",
    emojis: [
      { char: "❤️", keywords: "cœur amour rouge" },
      { char: "🧡", keywords: "cœur orange" },
      { char: "💛", keywords: "cœur jaune" },
      { char: "💚", keywords: "cœur vert" },
      { char: "💙", keywords: "cœur bleu" },
      { char: "💜", keywords: "cœur violet" },
      { char: "🖤", keywords: "cœur noir" },
      { char: "🤍", keywords: "cœur blanc" },
      { char: "🤎", keywords: "cœur marron" },
      { char: "💔", keywords: "cœur brisé triste" },
      { char: "❣️", keywords: "cœur exclamation" },
      { char: "💕", keywords: "deux cœurs amour" },
      { char: "💞", keywords: "cœurs tournants" },
      { char: "💓", keywords: "cœur battant" },
      { char: "💗", keywords: "cœur grandissant" },
      { char: "💖", keywords: "cœur scintillant" },
      { char: "💘", keywords: "cœur flèche cupidon" },
      { char: "💝", keywords: "cœur cadeau" },
      { char: "💟", keywords: "décoration cœur" },
      { char: "💌", keywords: "lettre d'amour" },
      { char: "💋", keywords: "bisou lèvres" },
      { char: "😻", keywords: "chat yeux cœur amour" },
      { char: "💑", keywords: "couple amoureux" },
      { char: "👩‍❤️‍👨", keywords: "couple homme femme" },
      { char: "👨‍❤️‍👨", keywords: "couple homme homme" },
      { char: "👩‍❤️‍👩", keywords: "couple femme femme" },
      { char: "💏", keywords: "couple qui s'embrasse" },
      { char: "💐", keywords: "bouquet fleurs" },
      { char: "💍", keywords: "bague fiançailles mariage" },
      { char: "💒", keywords: "église mariage" },
      { char: "👰", keywords: "mariée voile" },
      { char: "🤵", keywords: "marié costume" },
      { char: "👨‍👩‍👧", keywords: "famille parents fille" },
      { char: "👨‍👩‍👦", keywords: "famille parents fils" }
    ]
  },
  {
    id: "faith",
    label: "Foi",
    icon: "🙏",
    emojis: [
      { char: "✝️", keywords: "croix christianisme" },
      { char: "📖", keywords: "bible livre" },
      { char: "🕊️", keywords: "colombe paix esprit" },
      { char: "🙏", keywords: "prière merci" },
      { char: "⛪", keywords: "église" },
      { char: "🕯️", keywords: "bougie" },
      { char: "🌟", keywords: "étoile brillante" },
      { char: "✨", keywords: "étincelles brillant" },
      { char: "🌈", keywords: "arc-en-ciel promesse" },
      { char: "☀️", keywords: "soleil lumière" },
      { char: "🌙", keywords: "lune" },
      { char: "⭐", keywords: "étoile" },
      { char: "👼", keywords: "ange bébé" },
      { char: "😇", keywords: "ange innocent" },
      { char: "🎶", keywords: "musique louange" },
      { char: "🕉️", keywords: "symbole spirituel" }
    ]
  },
  {
    id: "animals",
    label: "Animaux",
    icon: "🐾",
    emojis: [
      { char: "🐶", keywords: "chien" },
      { char: "🐱", keywords: "chat" },
      { char: "🐭", keywords: "souris" },
      { char: "🐹", keywords: "hamster" },
      { char: "🐰", keywords: "lapin" },
      { char: "🦊", keywords: "renard" },
      { char: "🐻", keywords: "ours" },
      { char: "🐼", keywords: "panda" },
      { char: "🐨", keywords: "koala" },
      { char: "🐯", keywords: "tigre" },
      { char: "🦁", keywords: "lion" },
      { char: "🐮", keywords: "vache" },
      { char: "🐷", keywords: "cochon" },
      { char: "🐸", keywords: "grenouille" },
      { char: "🐵", keywords: "singe" },
      { char: "🐔", keywords: "poule" },
      { char: "🐧", keywords: "pingouin" },
      { char: "🐦", keywords: "oiseau" },
      { char: "🦅", keywords: "aigle" },
      { char: "🦉", keywords: "hibou" },
      { char: "🐴", keywords: "cheval" },
      { char: "🦄", keywords: "licorne" },
      { char: "🐝", keywords: "abeille" },
      { char: "🦋", keywords: "papillon" },
      { char: "🐢", keywords: "tortue" },
      { char: "🐍", keywords: "serpent" },
      { char: "🐳", keywords: "baleine" },
      { char: "🐬", keywords: "dauphin" },
      { char: "🐟", keywords: "poisson" },
      { char: "🦈", keywords: "requin" },
      { char: "🐘", keywords: "éléphant" },
      { char: "🦒", keywords: "girafe" }
    ]
  },
  {
    id: "food",
    label: "Nourriture",
    icon: "🍽️",
    emojis: [
      { char: "🍎", keywords: "pomme" },
      { char: "🍌", keywords: "banane" },
      { char: "🍊", keywords: "orange" },
      { char: "🍉", keywords: "pastèque" },
      { char: "🍇", keywords: "raisin" },
      { char: "🍓", keywords: "fraise" },
      { char: "🍍", keywords: "ananas" },
      { char: "🥭", keywords: "mangue" },
      { char: "🍕", keywords: "pizza" },
      { char: "🍔", keywords: "burger" },
      { char: "🍟", keywords: "frites" },
      { char: "🌭", keywords: "hot dog" },
      { char: "🥪", keywords: "sandwich" },
      { char: "🌮", keywords: "taco" },
      { char: "🍝", keywords: "pâtes spaghetti" },
      { char: "🍜", keywords: "nouilles soupe" },
      { char: "🍲", keywords: "ragoût plat" },
      { char: "🍗", keywords: "poulet viande" },
      { char: "🍖", keywords: "viande os" },
      { char: "🍚", keywords: "riz" },
      { char: "🥗", keywords: "salade" },
      { char: "🍞", keywords: "pain" },
      { char: "🥐", keywords: "croissant" },
      { char: "🧁", keywords: "cupcake gâteau" },
      { char: "🎂", keywords: "gâteau anniversaire" },
      { char: "🍰", keywords: "part de gâteau" },
      { char: "🍩", keywords: "beignet" },
      { char: "🍪", keywords: "cookie biscuit" },
      { char: "🍫", keywords: "chocolat" },
      { char: "🍿", keywords: "popcorn" },
      { char: "☕", keywords: "café" },
      { char: "🍵", keywords: "thé" },
      { char: "🥤", keywords: "boisson gazeuse" },
      { char: "🧃", keywords: "jus de fruit" },
      { char: "🍷", keywords: "vin" },
      { char: "🍾", keywords: "champagne célébration" }
    ]
  },
  {
    id: "activities",
    label: "Activités",
    icon: "⚽",
    emojis: [
      { char: "⚽", keywords: "football ballon" },
      { char: "🏀", keywords: "basketball" },
      { char: "🏈", keywords: "football américain" },
      { char: "⚾", keywords: "baseball" },
      { char: "🎾", keywords: "tennis" },
      { char: "🏐", keywords: "volleyball" },
      { char: "🏓", keywords: "ping pong tennis de table" },
      { char: "🏸", keywords: "badminton" },
      { char: "🥊", keywords: "boxe" },
      { char: "🎣", keywords: "pêche" },
      { char: "🎽", keywords: "course course à pied" },
      { char: "🏆", keywords: "trophée victoire" },
      { char: "🥇", keywords: "médaille or premier" },
      { char: "🎮", keywords: "jeux vidéo manette" },
      { char: "🎲", keywords: "dé jeu" },
      { char: "🎯", keywords: "cible fléchette" },
      { char: "🎨", keywords: "art peinture" },
      { char: "🎬", keywords: "cinéma film" },
      { char: "🎤", keywords: "microphone chant" },
      { char: "🎧", keywords: "écouteurs musique" },
      { char: "🎸", keywords: "guitare musique" },
      { char: "🎹", keywords: "piano musique" },
      { char: "🎉", keywords: "fête confettis célébration" },
      { char: "🎊", keywords: "confettis fête" },
      { char: "🎁", keywords: "cadeau" },
      { char: "🏖️", keywords: "plage vacances" },
      { char: "📚", keywords: "livres lecture étude" },
      { char: "✈️", keywords: "avion voyage" }
    ]
  },
  {
    id: "objects",
    label: "Objets",
    icon: "💡",
    emojis: [
      { char: "📱", keywords: "téléphone smartphone" },
      { char: "💻", keywords: "ordinateur portable" },
      { char: "⌚", keywords: "montre" },
      { char: "📷", keywords: "appareil photo" },
      { char: "🔋", keywords: "batterie" },
      { char: "💡", keywords: "ampoule idée" },
      { char: "🔦", keywords: "lampe torche" },
      { char: "🕯️", keywords: "bougie" },
      { char: "💰", keywords: "argent sac" },
      { char: "💵", keywords: "billet dollar" },
      { char: "💳", keywords: "carte bancaire" },
      { char: "✉️", keywords: "enveloppe message" },
      { char: "📩", keywords: "email reçu" },
      { char: "📦", keywords: "colis boîte" },
      { char: "🔑", keywords: "clé" },
      { char: "🔒", keywords: "cadenas fermé sécurité" },
      { char: "🔓", keywords: "cadenas ouvert" },
      { char: "🔨", keywords: "marteau outil" },
      { char: "🧰", keywords: "boîte à outils" },
      { char: "⏰", keywords: "réveil alarme" },
      { char: "⏳", keywords: "sablier temps" },
      { char: "🎓", keywords: "diplôme études" },
      { char: "💼", keywords: "mallette travail" },
      { char: "📅", keywords: "calendrier date" },
      { char: "📌", keywords: "épingle" },
      { char: "✏️", keywords: "crayon écrire" },
      { char: "📝", keywords: "note mémo" },
      { char: "📞", keywords: "téléphone appel" }
    ]
  },
  {
    id: "symbols",
    label: "Symboles",
    icon: "✅",
    emojis: [
      { char: "✅", keywords: "coche validé ok" },
      { char: "❌", keywords: "croix non refusé" },
      { char: "❗", keywords: "exclamation important" },
      { char: "❓", keywords: "question" },
      { char: "⚠️", keywords: "attention danger" },
      { char: "🚫", keywords: "interdit" },
      { char: "♻️", keywords: "recyclage" },
      { char: "🔴", keywords: "rond rouge" },
      { char: "🟢", keywords: "rond vert" },
      { char: "🟡", keywords: "rond jaune" },
      { char: "🔵", keywords: "rond bleu" },
      { char: "⚫", keywords: "rond noir" },
      { char: "⚪", keywords: "rond blanc" },
      { char: "🔺", keywords: "triangle rouge" },
      { char: "💯", keywords: "cent pourcent parfait" },
      { char: "🔥", keywords: "feu génial" },
      { char: "⭐", keywords: "étoile" },
      { char: "🌟", keywords: "étoile brillante" },
      { char: "💫", keywords: "étoile filante" },
      { char: "💥", keywords: "explosion boom" },
      { char: "💢", keywords: "colère symbole" },
      { char: "💦", keywords: "gouttes sueur" },
      { char: "💨", keywords: "vent rapide" },
      { char: "🕳️", keywords: "trou" },
      { char: "🔔", keywords: "cloche notification" },
      { char: "🔕", keywords: "cloche muette" },
      { char: "🆗", keywords: "ok" },
      { char: "🆕", keywords: "nouveau" },
      { char: "🔝", keywords: "top haut" },
      { char: "🔞", keywords: "interdit mineurs 18" },
      { char: "♥️", keywords: "cœur symbole" },
      { char: "♦️", keywords: "carreau symbole" }
    ]
  }
];
