export interface PhoneCountryCode {
  /** Code pays ISO alpha-2 — c'est ce que l'API Chariow attend dans `phone.country_code` (pas l'indicatif +XX). */
  code: string;
  label: string;
}

/** Tous les pays du monde, triés par ordre alphabétique (français), avec leur indicatif téléphonique — utilisé pour le paiement Chariow. */
export const PHONE_COUNTRY_CODES: PhoneCountryCode[] = [
  { code: "AF", label: "Afghanistan (+93)" },
  { code: "ZA", label: "Afrique du Sud (+27)" },
  { code: "AL", label: "Albanie (+355)" },
  { code: "DZ", label: "Algérie (+213)" },
  { code: "DE", label: "Allemagne (+49)" },
  { code: "AD", label: "Andorre (+376)" },
  { code: "AO", label: "Angola (+244)" },
  { code: "AI", label: "Anguilla (+1)" },
  { code: "AG", label: "Antigua-et-Barbuda (+1)" },
  { code: "SA", label: "Arabie saoudite (+966)" },
  { code: "AR", label: "Argentine (+54)" },
  { code: "AM", label: "Arménie (+374)" },
  { code: "AW", label: "Aruba (+297)" },
  { code: "AU", label: "Australie (+61)" },
  { code: "AT", label: "Autriche (+43)" },
  { code: "AZ", label: "Azerbaïdjan (+994)" },
  { code: "BS", label: "Bahamas (+1)" },
  { code: "BH", label: "Bahreïn (+973)" },
  { code: "BD", label: "Bangladesh (+880)" },
  { code: "BB", label: "Barbade (+1)" },
  { code: "BE", label: "Belgique (+32)" },
  { code: "BZ", label: "Belize (+501)" },
  { code: "BJ", label: "Bénin (+229)" },
  { code: "BM", label: "Bermudes (+1)" },
  { code: "BT", label: "Bhoutan (+975)" },
  { code: "BY", label: "Biélorussie (+375)" },
  { code: "BO", label: "Bolivie (+591)" },
  { code: "BA", label: "Bosnie-Herzégovine (+387)" },
  { code: "BW", label: "Botswana (+267)" },
  { code: "BR", label: "Brésil (+55)" },
  { code: "BN", label: "Brunei (+673)" },
  { code: "BG", label: "Bulgarie (+359)" },
  { code: "BF", label: "Burkina Faso (+226)" },
  { code: "BI", label: "Burundi (+257)" },
  { code: "KH", label: "Cambodge (+855)" },
  { code: "CM", label: "Cameroun (+237)" },
  { code: "CA", label: "Canada (+1)" },
  { code: "CV", label: "Cap-Vert (+238)" },
  { code: "CL", label: "Chili (+56)" },
  { code: "CN", label: "Chine (+86)" },
  { code: "CY", label: "Chypre (+357)" },
  { code: "CO", label: "Colombie (+57)" },
  { code: "KM", label: "Comores (+269)" },
  { code: "CG", label: "Congo-Brazzaville (+242)" },
  { code: "CD", label: "Congo-Kinshasa (+243)" },
  { code: "KP", label: "Corée du Nord (+850)" },
  { code: "KR", label: "Corée du Sud (+82)" },
  { code: "CR", label: "Costa Rica (+506)" },
  { code: "CI", label: "Côte d'Ivoire (+225)" },
  { code: "HR", label: "Croatie (+385)" },
  { code: "CU", label: "Cuba (+53)" },
  { code: "CW", label: "Curaçao (+599)" },
  { code: "DK", label: "Danemark (+45)" },
  { code: "DJ", label: "Djibouti (+253)" },
  { code: "DM", label: "Dominique (+1)" },
  { code: "EG", label: "Égypte (+20)" },
  { code: "AE", label: "Émirats arabes unis (+971)" },
  { code: "EC", label: "Équateur (+593)" },
  { code: "ER", label: "Érythrée (+291)" },
  { code: "ES", label: "Espagne (+34)" },
  { code: "EE", label: "Estonie (+372)" },
  { code: "SZ", label: "Eswatini (+268)" },
  { code: "VA", label: "État de la Cité du Vatican (+39)" },
  { code: "US", label: "États-Unis (+1)" },
  { code: "ET", label: "Éthiopie (+251)" },
  { code: "FJ", label: "Fidji (+679)" },
  { code: "FI", label: "Finlande (+358)" },
  { code: "FR", label: "France (+33)" },
  { code: "GA", label: "Gabon (+241)" },
  { code: "GM", label: "Gambie (+220)" },
  { code: "GE", label: "Géorgie (+995)" },
  { code: "GH", label: "Ghana (+233)" },
  { code: "GI", label: "Gibraltar (+350)" },
  { code: "GR", label: "Grèce (+30)" },
  { code: "GD", label: "Grenade (+1)" },
  { code: "GL", label: "Groenland (+299)" },
  { code: "GP", label: "Guadeloupe (+590)" },
  { code: "GU", label: "Guam (+1)" },
  { code: "GT", label: "Guatemala (+502)" },
  { code: "GG", label: "Guernesey (+44)" },
  { code: "GN", label: "Guinée (+224)" },
  { code: "GQ", label: "Guinée équatoriale (+240)" },
  { code: "GW", label: "Guinée-Bissau (+245)" },
  { code: "GY", label: "Guyana (+592)" },
  { code: "GF", label: "Guyane française (+594)" },
  { code: "HT", label: "Haïti (+509)" },
  { code: "HN", label: "Honduras (+504)" },
  { code: "HU", label: "Hongrie (+36)" },
  { code: "CX", label: "Île Christmas (+61)" },
  { code: "AC", label: "Île de l'Ascension (+247)" },
  { code: "IM", label: "Île de Man (+44)" },
  { code: "NF", label: "Île Norfolk (+672)" },
  { code: "AX", label: "Îles Åland (+358)" },
  { code: "KY", label: "Îles Caïmans (+1)" },
  { code: "CC", label: "Îles Cocos (+61)" },
  { code: "CK", label: "Îles Cook (+682)" },
  { code: "FO", label: "Îles Féroé (+298)" },
  { code: "FK", label: "Îles Malouines (+500)" },
  { code: "MP", label: "Îles Mariannes du Nord (+1)" },
  { code: "MH", label: "Îles Marshall (+692)" },
  { code: "SB", label: "Îles Salomon (+677)" },
  { code: "TC", label: "Îles Turques-et-Caïques (+1)" },
  { code: "VG", label: "Îles Vierges britanniques (+1)" },
  { code: "VI", label: "Îles Vierges des États-Unis (+1)" },
  { code: "IN", label: "Inde (+91)" },
  { code: "ID", label: "Indonésie (+62)" },
  { code: "IQ", label: "Irak (+964)" },
  { code: "IR", label: "Iran (+98)" },
  { code: "IE", label: "Irlande (+353)" },
  { code: "IS", label: "Islande (+354)" },
  { code: "IL", label: "Israël (+972)" },
  { code: "IT", label: "Italie (+39)" },
  { code: "JM", label: "Jamaïque (+1)" },
  { code: "JP", label: "Japon (+81)" },
  { code: "JE", label: "Jersey (+44)" },
  { code: "JO", label: "Jordanie (+962)" },
  { code: "KZ", label: "Kazakhstan (+7)" },
  { code: "KE", label: "Kenya (+254)" },
  { code: "KG", label: "Kirghizstan (+996)" },
  { code: "KI", label: "Kiribati (+686)" },
  { code: "XK", label: "Kosovo (+383)" },
  { code: "KW", label: "Koweït (+965)" },
  { code: "RE", label: "La Réunion (+262)" },
  { code: "LA", label: "Laos (+856)" },
  { code: "LS", label: "Lesotho (+266)" },
  { code: "LV", label: "Lettonie (+371)" },
  { code: "LB", label: "Liban (+961)" },
  { code: "LR", label: "Liberia (+231)" },
  { code: "LY", label: "Libye (+218)" },
  { code: "LI", label: "Liechtenstein (+423)" },
  { code: "LT", label: "Lituanie (+370)" },
  { code: "LU", label: "Luxembourg (+352)" },
  { code: "MK", label: "Macédoine du Nord (+389)" },
  { code: "MG", label: "Madagascar (+261)" },
  { code: "MY", label: "Malaisie (+60)" },
  { code: "MW", label: "Malawi (+265)" },
  { code: "MV", label: "Maldives (+960)" },
  { code: "ML", label: "Mali (+223)" },
  { code: "MT", label: "Malte (+356)" },
  { code: "MA", label: "Maroc (+212)" },
  { code: "MQ", label: "Martinique (+596)" },
  { code: "MU", label: "Maurice (+230)" },
  { code: "MR", label: "Mauritanie (+222)" },
  { code: "YT", label: "Mayotte (+262)" },
  { code: "MX", label: "Mexique (+52)" },
  { code: "FM", label: "Micronésie (+691)" },
  { code: "MD", label: "Moldavie (+373)" },
  { code: "MC", label: "Monaco (+377)" },
  { code: "MN", label: "Mongolie (+976)" },
  { code: "ME", label: "Monténégro (+382)" },
  { code: "MS", label: "Montserrat (+1)" },
  { code: "MZ", label: "Mozambique (+258)" },
  { code: "MM", label: "Myanmar (Birmanie) (+95)" },
  { code: "NA", label: "Namibie (+264)" },
  { code: "NR", label: "Nauru (+674)" },
  { code: "NP", label: "Népal (+977)" },
  { code: "NI", label: "Nicaragua (+505)" },
  { code: "NE", label: "Niger (+227)" },
  { code: "NG", label: "Nigeria (+234)" },
  { code: "NU", label: "Niue (+683)" },
  { code: "NO", label: "Norvège (+47)" },
  { code: "NC", label: "Nouvelle-Calédonie (+687)" },
  { code: "NZ", label: "Nouvelle-Zélande (+64)" },
  { code: "OM", label: "Oman (+968)" },
  { code: "UG", label: "Ouganda (+256)" },
  { code: "UZ", label: "Ouzbékistan (+998)" },
  { code: "PK", label: "Pakistan (+92)" },
  { code: "PW", label: "Palaos (+680)" },
  { code: "PA", label: "Panama (+507)" },
  { code: "PG", label: "Papouasie-Nouvelle-Guinée (+675)" },
  { code: "PY", label: "Paraguay (+595)" },
  { code: "NL", label: "Pays-Bas (+31)" },
  { code: "BQ", label: "Pays-Bas caribéens (+599)" },
  { code: "PE", label: "Pérou (+51)" },
  { code: "PH", label: "Philippines (+63)" },
  { code: "PL", label: "Pologne (+48)" },
  { code: "PF", label: "Polynésie française (+689)" },
  { code: "PR", label: "Porto Rico (+1)" },
  { code: "PT", label: "Portugal (+351)" },
  { code: "QA", label: "Qatar (+974)" },
  { code: "HK", label: "R.A.S. chinoise de Hong Kong (+852)" },
  { code: "MO", label: "R.A.S. chinoise de Macao (+853)" },
  { code: "CF", label: "République centrafricaine (+236)" },
  { code: "DO", label: "République dominicaine (+1)" },
  { code: "RO", label: "Roumanie (+40)" },
  { code: "GB", label: "Royaume-Uni (+44)" },
  { code: "RU", label: "Russie (+7)" },
  { code: "RW", label: "Rwanda (+250)" },
  { code: "EH", label: "Sahara occidental (+212)" },
  { code: "BL", label: "Saint-Barthélemy (+590)" },
  { code: "KN", label: "Saint-Christophe-et-Niévès (+1)" },
  { code: "SM", label: "Saint-Marin (+378)" },
  { code: "MF", label: "Saint-Martin (+590)" },
  { code: "SX", label: "Saint-Martin (partie néerlandaise) (+1)" },
  { code: "PM", label: "Saint-Pierre-et-Miquelon (+508)" },
  { code: "VC", label: "Saint-Vincent-et-les Grenadines (+1)" },
  { code: "SH", label: "Sainte-Hélène (+290)" },
  { code: "LC", label: "Sainte-Lucie (+1)" },
  { code: "SV", label: "Salvador (+503)" },
  { code: "WS", label: "Samoa (+685)" },
  { code: "AS", label: "Samoa américaines (+1)" },
  { code: "ST", label: "Sao Tomé-et-Principe (+239)" },
  { code: "SN", label: "Sénégal (+221)" },
  { code: "RS", label: "Serbie (+381)" },
  { code: "SC", label: "Seychelles (+248)" },
  { code: "SL", label: "Sierra Leone (+232)" },
  { code: "SG", label: "Singapour (+65)" },
  { code: "SK", label: "Slovaquie (+421)" },
  { code: "SI", label: "Slovénie (+386)" },
  { code: "SO", label: "Somalie (+252)" },
  { code: "SD", label: "Soudan (+249)" },
  { code: "SS", label: "Soudan du Sud (+211)" },
  { code: "LK", label: "Sri Lanka (+94)" },
  { code: "SE", label: "Suède (+46)" },
  { code: "CH", label: "Suisse (+41)" },
  { code: "SR", label: "Suriname (+597)" },
  { code: "SJ", label: "Svalbard et Jan Mayen (+47)" },
  { code: "SY", label: "Syrie (+963)" },
  { code: "TJ", label: "Tadjikistan (+992)" },
  { code: "TW", label: "Taïwan (+886)" },
  { code: "TZ", label: "Tanzanie (+255)" },
  { code: "TD", label: "Tchad (+235)" },
  { code: "CZ", label: "Tchéquie (+420)" },
  { code: "IO", label: "Territoire britannique de l'océan Indien (+246)" },
  { code: "PS", label: "Territoires palestiniens (+970)" },
  { code: "TH", label: "Thaïlande (+66)" },
  { code: "TL", label: "Timor oriental (+670)" },
  { code: "TG", label: "Togo (+228)" },
  { code: "TK", label: "Tokelau (+690)" },
  { code: "TO", label: "Tonga (+676)" },
  { code: "TT", label: "Trinité-et-Tobago (+1)" },
  { code: "TA", label: "Tristan da Cunha (+290)" },
  { code: "TN", label: "Tunisie (+216)" },
  { code: "TM", label: "Turkménistan (+993)" },
  { code: "TR", label: "Turquie (+90)" },
  { code: "TV", label: "Tuvalu (+688)" },
  { code: "UA", label: "Ukraine (+380)" },
  { code: "UY", label: "Uruguay (+598)" },
  { code: "VU", label: "Vanuatu (+678)" },
  { code: "VE", label: "Venezuela (+58)" },
  { code: "VN", label: "Viêt Nam (+84)" },
  { code: "WF", label: "Wallis-et-Futuna (+681)" },
  { code: "YE", label: "Yémen (+967)" },
  { code: "ZM", label: "Zambie (+260)" },
  { code: "ZW", label: "Zimbabwe (+263)" }
];
